### ISSUE TITLE
Stickers not completely blocked

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/tdesktop#11]
Most of the sticker blocking is working.  There is just a couple of small bugs that I've stumbled across.  On the profile that I'm including screenshots from we have stickers blocked.

![image](https://user-images.githubusercontent.com/1034679/50168046-c33f2480-02a7-11e9-930f-b783a2fbb1a5.png)

![image](https://user-images.githubusercontent.com/1034679/50168088-d4883100-02a7-11e9-9bff-455115def0b0.png)

**Comment by patriciy** [comment]
@dkwiebe is this still relevant?

**Comment by dkwiebe** [comment]
@patriciy Yes, it is.
![image](https://user-images.githubusercontent.com/1034679/50912310-190e7480-13ef-11e9-92b8-a4d560c68caf.png)

**Comment by dkwiebe** [comment]
This is mostly resolved.  I see it showing up one place yet.

![image](https://user-images.githubusercontent.com/1034679/52159657-9df25400-2664-11e9-83e7-603e053491b0.png)

**Comment by dkwiebe** [comment]
This is patched in 1.6.1
