### ISSUE TITLE
Incorrect Icon

### ISSUE THREAD

**Issue by dkwiebe** [cloudveiltech/tdesktop#13]
The Windows version is displaying the following icon in the taskbar.
![image](https://user-images.githubusercontent.com/1034679/52103232-e0069180-25a1-11e9-8d35-94a8b3847eb8.png)

**Comment by patriciy** [comment]
What windows version is it?

**Comment by dkwiebe** [comment]
I'm on Windows 10.  CVM is 1.5.2.  Should we start adding build numbers in the ui?  On a different computer the icon shows correctly but if I hover on it, it shows Telegram Desktop.  

This might be related to icon resolutions as the computer I've having trouble on has a 4K monitor.

**Comment by dkwiebe** [comment]
It seems to be working for me now.  Not sure what was going on.
