### ISSUE TITLE
Stickers not working when stickers are enabled.

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/tdesktop#14]
![image](https://user-images.githubusercontent.com/7513273/52575949-c6a4e700-2de4-11e9-85b3-8dcfa85a8475.png)

Stickers are enabled on this user.

**Comment by montesound** [comment]
![image](https://user-images.githubusercontent.com/7513273/52576003-e6d4a600-2de4-11e9-9143-7eaae66024e6.png)

**Comment by dkwiebe** [comment]
@patriciy Stickers are mostly working but I'm going to send a few screenshots to illustrate a small problem.  It does the same thing or at least something very similar on Android.  On the bottom of this screenshot, you can see a sticker that has loaded.  If I switch out of the chat and get back into it then it might show up.

![image](https://user-images.githubusercontent.com/1034679/59979489-db209980-95a5-11e9-8e04-c339394cdae8.png)

**Comment by patriciy** [comment]
@montesound I believe all stickersets are blocked (filtered out) on server for this user. 
Can you try with https://t.me/addstickers/BoyWhoLived ? This stickerset shown fine for me.

@dkwiebe I don't fully understand the issue. Can you provide steps/videos to reproduce?
