### ISSUE TITLE
Complete automatic updates

### ISSUE THREAD

**Issue by montesound** [cloudveiltech/tdesktop#3]
Here is the download location.
https://www.cloudveil.org/messenger_downloads/cloudveil_messenger_setup.exe

**Comment by montesound** [comment]
1) app send update request like update_check?currentversion=12442
2) Server returns either 200 (there's an update) or 404 (no updates for this version)
3) if it's 200 - server returns also installer url
4) App shows popup "update now! Click here!"
5) user clicks on button and redirected to download url in browser

**Comment by patriciy** [comment]
https://manage.cloudveil.org/api/v1/messenger/updates/windows?current_version=12442 or https://manage.cloudveil.org/api/v1/messenger/updates/windows?current_version=12441

**Comment by dkwiebe** [comment]
This needs to be reimplemented in the latest version.  It's pulling updates straight from Telegram.

**Comment by patriciy** [comment]
Should be ok now
