### ISSUE TITLE
macOS notification badge count wrong

### ISSUE THREAD

**Issue by thetmtech** [cloudveiltech/tdesktop#7]
macOS version 10.14 Beta

CloudVeil Messenger 1.3.10 alpha notification count is showing a negative number, increasing every time a notification is opened.
<img width="138" alt="screen shot 2018-08-22 at 10 03 05 am" src="https://user-images.githubusercontent.com/26845997/44475862-641c1c80-a5f3-11e8-942d-9d0327d9d9d5.png">

**Comment by dkwiebe** [comment]
@tysonkcv Is this still an issue?

**Comment by thetmtech** [comment]
I'm still seeing a negative count sometimes, but it does eventually clear out.

**Comment by thetmtech** [comment]
Closing for now, seems to be correct now.
